Ssa knee
LinkedEarth/Pyleoclim_util pull request #345
Opened 2023-02-23 00:02 UTC by alexkjames

Include knee finding truncation method in ssa. Closes #331 

Note: This adds [kneed](https://pypi.org/project/kneed/) to our dependencies. It looks like a well maintained package, but nonetheless its a new thing that can break.

2023-02-23 23:59 UTC, CommonClimate requested changes
Looks like a thorough job, but I wonder how that looks in practice. Can you please provide:

- a notebook example
- guidance in the docstring about when to use that selection criterion
?
That is, if it seems a lot more objective and performs better than Kaiser or var, let's state that and encourage users to use this as the preferred truncation option. Also, there needs to be a warning about setting `online` to False if users are going to apply this recursively (or perhaps, warn them not to do that...).

2023-02-24 01:49 UTC, alexkjames commented
Re the notebook example, see the attached zip file.

I've also pushed some small changes to the docstring in my most recent commit. Let me know if they seem adequate, happy to elaborate or change them.

[ssa_knee_pyleoclim.ipynb.zip](https://github.com/LinkedEarth/Pyleoclim_util/files/10819939/ssa_knee_pyleoclim.ipynb.zip)

2023-02-24 05:28 UTC, CommonClimate commented
That's a convincing argument! I would just update the docstring to say that, while no truncation method is imposed by default, if the goal is to enhance the S/N ratio and reconstruct a smooth version of the attractor's skeleton, then the knee-finding method is a good compromise between objectivity and efficiency. Definitely  include this in the PyleoTutorial!

2023-02-24 05:28 UTC, CommonClimate approved these changes

2023-02-24 17:48 UTC, merged