time coverage plots
LinkedEarth/Pyleoclim_util pull request #500
Opened 2024-01-06 00:36 UTC by alexkjames

add time_coverage_plot to multiple series and time_geo_plot to multiple geo series

Addresses issue #483

2024-01-06 01:47 UTC, CommonClimate requested changes
Hey Alex, 
this seems great, but needs docstring examples so it can easily be tested and used.
Can you re-purpose examples from MS.plot() and MGS.plot()?
Julien

2024-01-08 23:30 UTC, alexkjames commented
> Hey Alex, this seems great, but needs docstring examples so it can easily be tested and used. Can you re-purpose examples from MS.plot() and MGS.plot()? Julien

addressed in the most recent two commits (b3264e5 and abf528d)

2024-01-10 02:03 UTC, CommonClimate approved these changes

2024-01-10 02:03 UTC, CommonClimate commented
Thank you! This does it for now - we can always modify later based on user feedback.

2024-01-10 22:48 UTC, merged